import { ArchiveItem } from './types';

export const INITIAL_ARCHIVE_ITEMS: ArchiveItem[] = [
  {
    id: 'arch-01',
    title: '모놀리식 콘크리트 하우스',
    description: '빛과 그림자의 극적인 대비를 이끌어내는 브루탈리즘 양식의 현대 주거 건축 연구.',
    content: '모속적인 직사각형의 슬라브와 거친 노출 콘크리트 질감을 정밀하게 다듬어 지은 이 주택은 절제미의 정수를 보여줍니다. 자연광이 좁은 틈새 and 커다란 통창을 통과하며 시간에 따라 내부에 각기 다른 기하학적 형태의 그림자를 만들어내도록 설계되었습니다. 단순함을 넘어서 재료 본연의 힘과 공간감에 깊이 집중하도록 이끕니다.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    category: 'Plane',
    tags: ['Brutalism', 'Concrete', 'Minimalist', 'Lighting'],
    date: '2026-04-12',
    createdAt: 1775980800000,
    author: 'Studio Mono',
    location: 'Copenhagen, Denmark',
    usedFonts: 'Playfair Display, Inter',
    colorCode: '#18181B, #E4E4E7, #71717A'
  },
  {
    id: 'obj-01',
    title: '클래식 레트로 링 오디오 시스템',
    description: '디터 람스의 디자인 철학인 "Less, but better"에 헌사하는 미니멀 아날로그 스피커 리디자인.',
    content: '복잡한 다이얼과 불필요한 장식을 배제하고 기하학적 완벽함과 직관적인 버튼 배치에 중점을 두어 오직 청각적 경험과 평온함만을 전달하는 탁상용 오디오 시스템입니다. 촉각 피드백을 극대화하는 알루미늄 다이얼과 울림을 극대화한 전면 타공 패널은 미드센추리 모던 감수성을 재해석하는 핵심 키워드입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    category: 'Typography',
    tags: ['Dieter Rams', 'Analog', 'Aluminium', 'Industrial'],
    date: '2026-05-18',
    createdAt: 1779091200000,
    author: 'Jonas Keller',
    location: 'Munich, Germany',
    usedFonts: 'Helvetica Neue, Haas Grotesk',
    colorCode: '#D4AF37, #27272A, #FAFAFA'
  },
  {
    id: 'tech-01',
    title: 'HHKB 레이아웃 무선 기계식 키보드',
    description: '프로그래머들의 이상적인 타건 환경을 위해 정제된 무광 가스켓 마운트 키보드.',
    content: '손목의 움직임을 최소화하고 오타를 줄여주며 인체공학적 피로를 극대화로 줄여주는 최적화 레이아웃을 채택한 장치입니다. 무광 가니시 플라스틱 하우징과 황동 플레이트의 조화로운 레이어 구성을 통해 깊고 묵직한 하이 피치 타건음을 들려줍니다. 키캡 역시 장인의 실크 인쇄를 통해 정적인 미감과 장인정신을 구현해 냈습니다.',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80',
    category: 'Image',
    tags: ['Mechanical Keyboards', 'Gasket Mount', 'Workspace', 'Brass'],
    date: '2026-06-01',
    createdAt: 1780300800000,
    author: 'Sato Workshop',
    location: 'Tokyo, Japan',
    usedFonts: 'JetBrains Mono, Inter',
    colorCode: '#F5F5F7, #222222, #C5A880'
  },
  {
    id: 'nature-01',
    title: '태고의 고요함을 품은 안개 호수',
    description: '미세한 자연의 대칭과 부유하는 아침 안개에서 발견한 시각적 명상.',
    content: '인간의 손길이 닿지 않은 태고의 차가운 숲 가운데 자리 잡은 거울 같은 호수입니다. 이른 새벽 옅게 피어나는 수면 위의 안개와 끝없이 펼쳐진 수중 대칭은 보는 이로 하여금 깊은 내적 명상 상태를 유도합니다. 이 시각 기록은 정지된 화면 속에서도 미세하게 흐르는 공기의 파동과 영원한 고요의 순간을 포착했습니다.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    category: 'Collage',
    tags: ['Meditation', 'Landscape', 'Ethereal', 'Symmetry'],
    date: '2026-02-15',
    createdAt: 1771113600000,
    author: 'Evelyn Parker',
    location: 'Alberta, Canada',
    usedFonts: 'Space Grotesk, Inter',
    colorCode: '#0D2C30, #2E5C5E, #ECFDF5'
  },
  {
    id: 'arch-02',
    title: '스노헤타 스타일 미니멀 아트 뮤지엄',
    description: '지평선 아래로 가라앉아 대지와 완전히 통합된 형태의 저진동 갤러리 미술관.',
    content: '자연과 인간 문명의 인위적인 구분을 없애기 위해 경사면에 밀착하여 지어진 갤러리 건축 프로젝트입니다. 거친 천연 화강암 블록과 밝은 참나무 기둥들이 결합해 내부에서는 마치 거대한 지하 신전에 비스듬히 들어오는 천연 햇빛을 올려다보는 느낌을 전해줍니다. 현대 공간 예술가들이 가장 사랑하는 지향점 중 하나입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    category: 'Plane',
    tags: ['Museum', 'Spacious', 'Snohetta', 'Granite'],
    date: '2026-01-20',
    createdAt: 1768867200000,
    author: 'Kjetil Thorsen',
    location: 'Oslo, Norway',
    usedFonts: 'Space Grotesk, Playfair Display',
    colorCode: '#FAF9F6, #1C1917, #78716C'
  },
  {
    id: 'obj-02',
    title: '미드센추리 모던 태닝 파수아 체어',
    description: '우아한 유선형의 금속 튜블러 프레임과 점진적으로 가죽 표면이 깊어지는 허니 가죽 슬링 세라믹이 어울린 휴식용 안락의자입니다.',
    content: '1950년대 클래식 인더스트리얼 거장들의 기풍을 빌어 제작되었으며, 견고하게 조여진 황동 리벳과 손바느질로 스티치 처리된 마감에서 대를 이어 소구할 수 있는 무한한 아름다움을 가집니다.',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80',
    category: 'Typography',
    tags: ['Mid-Century', 'Leather Chair', 'Furniture', 'Tubular Steel'],
    date: '2026-03-05',
    createdAt: 1772668800000,
    author: 'Hale & Co.',
    location: 'Milan, Italy',
    usedFonts: 'Cinzel, Inter',
    colorCode: '#B45309, #27272A, #F5F5F4'
  },
  {
    id: 'tech-02',
    title: '네온 반사의 일렉트로 미장센',
    description: '비에 젖은 밤거리가 모니터 뒤편 광원과 융합하는 사이비 가상 현실 아트웍.',
    content: '사이버펑크적인 무아와 아날로그의 물리적 디스플레이가 충돌하는 미래형 작업실 인테리어를 탐구한 비주얼 기록입니다. 형광 마젠타와 일렉트릭 블루 색상이 반사율 높은 메탈 키보드 패드 위를 흐르며 심야의 차가운 정취와 첨단 기재들이 공존하는 독창적인 고스풍 미래 스튜디오 무드를 풍깁니다.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
    category: 'Image',
    tags: ['Cyberpunk', 'Neon', 'Vaporwave', 'Ambient Lighting'],
    date: '2026-05-30',
    createdAt: 1780128000000,
    author: 'Reza Wong',
    location: 'Singapore',
    usedFonts: 'JetBrains Mono, Fira Code',
    colorCode: '#F43F5E, #3B82F6, #09090B'
  },
  {
    id: 'nature-02',
    title: '침엽수림 너머의 에메랄드 캐노피',
    description: '빛과 비옥함이 깊어지는 신비스러운 원시 숲길이 전해주는 피톤치드 에세이.',
    content: '바스락거리는 양치식물과 이끼를 머금은 거대한 삼나무 기둥들 사이로 스며드는 상쾌하고 차가운 아침 공기. 이 한 장의 아카이빙은 눈으로 보는 것만으로도 자연이 선사하는 가장 풍요로운 평화와 산림욕을 그대로 안방으로 운송합니다. 무광 프레임으로 가두어 보관하기에 가장 아름다운 풍경 사진 중 하나입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1200&q=80',
    category: 'Theme',
    tags: ['Forest', 'Greenery', 'Morning Walk', 'Pristine'],
    date: '2026-01-08',
    createdAt: 1767830400000,
    author: 'Linnea Lindqvist',
    location: 'Kiruna, Sweden',
    usedFonts: 'Playfair Display, Inter',
    colorCode: '#064E3B, #10B981, #F0FDF4'
  }
];

export const CATEGORIES = ['All', 'Plane', 'Typography', 'Image', 'Collage', 'Theme'];
